import type { CrochetItem } from './types';

export const PRODUCTS: CrochetItem[] = [
  {
    id: 1,
    name: 'Sunny the Amigurumi Bee',
    description: 'A cheerful and cuddly bee, perfect for brightening up any room. Hand-stitched with soft cotton yarn.',
    price: 65,
    imageUrl: 'https://picsum.photos/seed/bee/400/400',
  },
  {
    id: 2,
    name: 'Cozy Winter Scarf',
    description: 'Wrap yourself in warmth with this chunky, hand-crocheted scarf. Made from a premium wool blend.',
    price: 90,
    imageUrl: 'https://picsum.photos/seed/scarf/400/400',
  },
  {
    id: 3,
    name: 'Boho Plant Hanger',
    description: 'A stylish and sturdy macrame-style plant hanger to display your favorite greenery. Fits various pot sizes.',
    price: 75,
    imageUrl: 'https://picsum.photos/seed/planthanger/400/400',
  },
  {
    id: 4,
    name: 'Baby Yoda Plushie',
    description: 'The cutest companion in the galaxy! This adorable Baby Yoda inspired plushie is a must-have for fans.',
    price: 85,
    imageUrl: 'https://picsum.photos/seed/yoda/400/400',
  },
  {
    id: 5,
    name: 'Pastel Rainbow Blanket',
    description: 'A soft, lightweight baby blanket made with gentle pastel colors. Ideal for strollers and cribs.',
    price: 95,
    imageUrl: 'https://picsum.photos/seed/blanket/400/400',
  },
  {
    id: 6,
    name: 'Market Tote Bag',
    description: 'An eco-friendly and expandable tote bag, perfect for trips to the farmers market or the beach.',
    price: 70,
    imageUrl: 'https://picsum.photos/seed/bag/400/400',
  },
  {
    id: 7,
    name: 'Mushroom Friend',
    description: 'A whimsical and cute mushroom friend with a friendly smile. Great for cottagecore decor.',
    price: 55,
    imageUrl: 'https://picsum.photos/seed/mushroom/400/400',
  },
  {
    id: 8,
    name: 'Chunky Knit Beanie',
    description: 'Stay warm and stylish with this handmade beanie featuring a classic cable-knit pattern and a fluffy pom-pom.',
    price: 80,
    imageUrl: 'https://picsum.photos/seed/beanie/400/400',
  },
  { id: 9, name: 'Octavius the Octopus', description: 'A charming eight-legged friend, perfect for cuddles. Made with super soft yarn.', price: 70, imageUrl: 'https://picsum.photos/seed/octopus/400/400' },
  { id: 10, name: 'Jellyfish Dream', description: 'A whimsical hanging jellyfish with flowing tentacles. Adds a touch of magic to any room.', price: 60, imageUrl: 'https://picsum.photos/seed/jellyfish/400/400' },
  { id: 11, name: 'T-Rex Buddy', description: 'A not-so-scary dinosaur plushie ready for prehistoric adventures.', price: 85, imageUrl: 'https://picsum.photos/seed/dino/400/400' },
  { id: 12, name: 'Sleepy Sloth', description: 'This slow-moving friend loves to hang around and nap. Incredibly soft and huggable.', price: 75, imageUrl: 'https://picsum.photos/seed/sloth/400/400' },
  { id: 13, name: 'Whale of a Time', description: 'A giant, gentle whale plush. Perfect as a soft pillow or a companion.', price: 95, imageUrl: 'https://picsum.photos/seed/whale/400/400' },
  { id: 14, name: 'Penguin Pal', description: 'A dapper penguin, ready to waddle his way into your heart.', price: 65, imageUrl: 'https://picsum.photos/seed/penguin/400/400' },
  { id: 15, name: 'Sea Turtle Traveler', description: 'A wise and gentle sea turtle with a beautifully patterned shell.', price: 80, imageUrl: 'https://picsum.photos/seed/turtle/400/400' },
  { id: 16, name: 'Foxy Friend', description: 'A clever and cute fox amigurumi with a bushy tail.', price: 70, imageUrl: 'https://picsum.photos/seed/fox/400/400' },
  { id: 17, name: 'Sunflower Coasters (Set of 4)', description: 'Brighten up your coffee table with these cheerful sunflower coasters.', price: 55, imageUrl: 'https://picsum.photos/seed/coasters/400/400' },
  { id: 18, name: 'Chunky Knit Throw Pillow', description: 'An incredibly soft and stylish pillow to add texture to your sofa or bed.', price: 90, imageUrl: 'https://picsum.photos/seed/pillow/400/400' },
  { id: 19, name: 'Nesting Storage Baskets', description: 'A set of three versatile baskets for organizing toys, yarn, or accessories.', price: 85, imageUrl: 'https://picsum.photos/seed/baskets/400/400' },
  { id: 20, name: 'Luxury Spa Washcloths', description: 'A set of soft, textured washcloths to elevate your daily routine.', price: 60, imageUrl: 'https://picsum.photos/seed/washcloth/400/400' },
  { id: 21, name: 'Mandala Wall Hanging', description: 'An intricate and beautiful mandala to create a peaceful focal point in any room.', price: 95, imageUrl: 'https://picsum.photos/seed/mandala/400/400' },
  { id: 22, name: 'Cactus Collection', description: 'A trio of cute, no-maintenance crochet cacti in tiny terracotta pots.', price: 70, imageUrl: 'https://picsum.photos/seed/cactus/400/400' },
  { id: 23, name: 'Fingerless Gloves', description: 'Keep your hands warm while your fingers stay free. Features a lovely stitch pattern.', price: 50, imageUrl: 'https://picsum.photos/seed/gloves/400/400' },
  { id: 24, name: 'Oversized Cardigan', description: 'The perfect cozy cardigan for lazy weekends and chilly evenings.', price: 100, imageUrl: 'https://picsum.photos/seed/cardigan/400/400' },
  { id: 25, name: 'Cozy Slipper Socks', description: 'Warm and comfortable slipper socks with non-slip soles.', price: 65, imageUrl: 'https://picsum.photos/seed/slippers/400/400' },
  { id: 26, name: 'Cat-Ear Beanie', description: 'A playful and cute beanie with subtle cat ears. Fun for all ages.', price: 75, imageUrl: 'https://picsum.photos/seed/catbeanie/400/400' },
  { id: 27, name: 'Infinity Scarf', description: 'A stylish and versatile infinity scarf that can be looped for extra warmth.', price: 80, imageUrl: 'https://picsum.photos/seed/infinityscarf/400/400' },
  { id: 28, name: 'Summer Festival Top', description: 'A light and airy crochet top, perfect for summer concerts and festivals.', price: 90, imageUrl: 'https://picsum.photos/seed/croptop/400/400' },
  { id: 29, name: 'Unicorn Lovey', description: 'A magical unicorn combined with a small security blanket for your little one.', price: 70, imageUrl: 'https://picsum.photos/seed/lovey/400/400' },
  { id: 30, name: 'Wooden Ring Baby Rattle', description: 'A gentle sounding rattle with soft crochet elements, safe for teething babies.', price: 55, imageUrl: 'https://picsum.photos/seed/rattle/400/400' },
  { id: 31, name: 'Play Food - Breakfast Set', description: 'A fun set including a fried egg, bacon, and a pancake for imaginative play.', price: 65, imageUrl: 'https://picsum.photos/seed/playfood/400/400' },
  { id: 32, name: 'Baby Booties', description: 'Adorable and soft booties to keep tiny toes warm. A perfect baby shower gift.', price: 50, imageUrl: 'https://picsum.photos/seed/booties/400/400' },
  { id: 33, name: 'Star Garland', description: 'A sweet garland of crochet stars to decorate a nursery or child\'s room.', price: 60, imageUrl: 'https://picsum.photos/seed/garland/400/400' },
  { id: 34, name: 'Friendly Ghost', description: 'A cute, not-spooky ghost plushie that is perfect for Halloween or all year round.', price: 55, imageUrl: 'https://picsum.photos/seed/ghost/400/400' },
  { id: 35, name: 'Granny Square Cushion Cover', description: 'A classic, colorful granny square cushion cover to add a retro vibe to your home.', price: 85, imageUrl: 'https://picsum.photos/seed/grannysquare/400/400' },
  { id: 36, name: 'Amigurumi Avocado', description: 'A cute avocado duo that fits together. A quirky and fun gift.', price: 60, imageUrl: 'https://picsum.photos/seed/avocado/400/400' },
  { id: 37, name: 'Laptop Sleeve', description: 'A soft and protective crochet sleeve to keep your laptop safe and stylish.', price: 90, imageUrl: 'https://picsum.photos/seed/laptopsleeve/400/400' },
  { id: 38, name: 'Reading Owl Bookmark', description: 'A wise owl to hold your place in your favorite book.', price: 50, imageUrl: 'https://picsum.photos/seed/bookmark/400/400' },
  { id: 39, name: 'Daisy Chain Headband', description: 'A beautiful and delicate headband adorned with crochet daisies.', price: 55, imageUrl: 'https://picsum.photos/seed/headband/400/400' },
  { id: 40, name: 'Hedgehog Pincushion', description: 'A cute little hedgehog to hold your pins and needles.', price: 60, imageUrl: 'https://picsum.photos/seed/hedgehog/400/400' },
  { id: 41, name: 'Rainbow Wall Hanging', description: 'A beautiful textured rainbow to bring color and joy to your walls.', price: 80, imageUrl: 'https://picsum.photos/seed/rainbow/400/400' },
  { id: 42, name: 'Striped Beach Bag', description: 'A large, sturdy bag perfect for carrying towels, sunscreen, and books to the beach.', price: 95, imageUrl: 'https://picsum.photos/seed/beachbag/400/400' },
  { id: 43, name: 'Pumpkin Patch Trio', description: 'A set of three decorative crochet pumpkins, perfect for autumn decor.', price: 70, imageUrl: 'https://picsum.photos/seed/pumpkin/400/400' },
  { id: 44, name: 'Cup Cozy', description: 'A reusable sleeve for your coffee cup. Eco-friendly and stylish.', price: 50, imageUrl: 'https://picsum.photos/seed/cupcozy/400/400' },
  { id: 45, name: 'Little Mermaid Doll', description: 'A beautifully crafted amigurumi mermaid doll with flowing hair and a shimmery tail.', price: 90, imageUrl: 'https://picsum.photos/seed/mermaid/400/400' },
  { id: 46, name: 'Bernie\'s Mittens Replica', description: 'A replica of the famous mittens, cozy and perfect for a bit of fun.', price: 75, imageUrl: 'https://picsum.photos/seed/mittens/400/400' },
  { id: 47, name: 'Froggy Bucket Hat', description: 'A fun and trendy bucket hat with cute frog eyes on top.', price: 80, imageUrl: 'https://picsum.photos/seed/froghat/400/400' },
  { id: 48, name: 'Gnome for the Holidays', description: 'A festive gnome with a long beard and pointy hat, perfect for Christmas.', price: 65, imageUrl: 'https://picsum.photos/seed/gnome/400/400' },
];

export const PAYMENT_PHONE_NUMBER = '9009290796';
